# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _image_editor
else:
    import _image_editor

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _image_editor.delete_SwigPyIterator

    def value(self):
        return _image_editor.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _image_editor.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _image_editor.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _image_editor.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _image_editor.SwigPyIterator_equal(self, x)

    def copy(self):
        return _image_editor.SwigPyIterator_copy(self)

    def next(self):
        return _image_editor.SwigPyIterator_next(self)

    def __next__(self):
        return _image_editor.SwigPyIterator___next__(self)

    def previous(self):
        return _image_editor.SwigPyIterator_previous(self)

    def advance(self, n):
        return _image_editor.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _image_editor.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _image_editor.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _image_editor.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _image_editor.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _image_editor.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _image_editor.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _image_editor:
_image_editor.SwigPyIterator_swigregister(SwigPyIterator)
SHARED_PTR_DISOWN = _image_editor.SHARED_PTR_DISOWN
class FloatVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _image_editor.FloatVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _image_editor.FloatVector___nonzero__(self)

    def __bool__(self):
        return _image_editor.FloatVector___bool__(self)

    def __len__(self):
        return _image_editor.FloatVector___len__(self)

    def __getslice__(self, i, j):
        return _image_editor.FloatVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _image_editor.FloatVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _image_editor.FloatVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _image_editor.FloatVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _image_editor.FloatVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _image_editor.FloatVector___setitem__(self, *args)

    def pop(self):
        return _image_editor.FloatVector_pop(self)

    def append(self, x):
        return _image_editor.FloatVector_append(self, x)

    def empty(self):
        return _image_editor.FloatVector_empty(self)

    def size(self):
        return _image_editor.FloatVector_size(self)

    def swap(self, v):
        return _image_editor.FloatVector_swap(self, v)

    def begin(self):
        return _image_editor.FloatVector_begin(self)

    def end(self):
        return _image_editor.FloatVector_end(self)

    def rbegin(self):
        return _image_editor.FloatVector_rbegin(self)

    def rend(self):
        return _image_editor.FloatVector_rend(self)

    def clear(self):
        return _image_editor.FloatVector_clear(self)

    def get_allocator(self):
        return _image_editor.FloatVector_get_allocator(self)

    def pop_back(self):
        return _image_editor.FloatVector_pop_back(self)

    def erase(self, *args):
        return _image_editor.FloatVector_erase(self, *args)

    def __init__(self, *args):
        _image_editor.FloatVector_swiginit(self, _image_editor.new_FloatVector(*args))

    def push_back(self, x):
        return _image_editor.FloatVector_push_back(self, x)

    def front(self):
        return _image_editor.FloatVector_front(self)

    def back(self):
        return _image_editor.FloatVector_back(self)

    def assign(self, n, x):
        return _image_editor.FloatVector_assign(self, n, x)

    def resize(self, *args):
        return _image_editor.FloatVector_resize(self, *args)

    def insert(self, *args):
        return _image_editor.FloatVector_insert(self, *args)

    def reserve(self, n):
        return _image_editor.FloatVector_reserve(self, n)

    def capacity(self):
        return _image_editor.FloatVector_capacity(self)
    __swig_destroy__ = _image_editor.delete_FloatVector

# Register FloatVector in _image_editor:
_image_editor.FloatVector_swigregister(FloatVector)
class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _image_editor.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _image_editor.StringVector___nonzero__(self)

    def __bool__(self):
        return _image_editor.StringVector___bool__(self)

    def __len__(self):
        return _image_editor.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _image_editor.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _image_editor.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _image_editor.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _image_editor.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _image_editor.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _image_editor.StringVector___setitem__(self, *args)

    def pop(self):
        return _image_editor.StringVector_pop(self)

    def append(self, x):
        return _image_editor.StringVector_append(self, x)

    def empty(self):
        return _image_editor.StringVector_empty(self)

    def size(self):
        return _image_editor.StringVector_size(self)

    def swap(self, v):
        return _image_editor.StringVector_swap(self, v)

    def begin(self):
        return _image_editor.StringVector_begin(self)

    def end(self):
        return _image_editor.StringVector_end(self)

    def rbegin(self):
        return _image_editor.StringVector_rbegin(self)

    def rend(self):
        return _image_editor.StringVector_rend(self)

    def clear(self):
        return _image_editor.StringVector_clear(self)

    def get_allocator(self):
        return _image_editor.StringVector_get_allocator(self)

    def pop_back(self):
        return _image_editor.StringVector_pop_back(self)

    def erase(self, *args):
        return _image_editor.StringVector_erase(self, *args)

    def __init__(self, *args):
        _image_editor.StringVector_swiginit(self, _image_editor.new_StringVector(*args))

    def push_back(self, x):
        return _image_editor.StringVector_push_back(self, x)

    def front(self):
        return _image_editor.StringVector_front(self)

    def back(self):
        return _image_editor.StringVector_back(self)

    def assign(self, n, x):
        return _image_editor.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _image_editor.StringVector_resize(self, *args)

    def insert(self, *args):
        return _image_editor.StringVector_insert(self, *args)

    def reserve(self, n):
        return _image_editor.StringVector_reserve(self, n)

    def capacity(self):
        return _image_editor.StringVector_capacity(self)
    __swig_destroy__ = _image_editor.delete_StringVector

# Register StringVector in _image_editor:
_image_editor.StringVector_swigregister(StringVector)
class SizeTVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _image_editor.SizeTVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _image_editor.SizeTVector___nonzero__(self)

    def __bool__(self):
        return _image_editor.SizeTVector___bool__(self)

    def __len__(self):
        return _image_editor.SizeTVector___len__(self)

    def __getslice__(self, i, j):
        return _image_editor.SizeTVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _image_editor.SizeTVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _image_editor.SizeTVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _image_editor.SizeTVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _image_editor.SizeTVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _image_editor.SizeTVector___setitem__(self, *args)

    def pop(self):
        return _image_editor.SizeTVector_pop(self)

    def append(self, x):
        return _image_editor.SizeTVector_append(self, x)

    def empty(self):
        return _image_editor.SizeTVector_empty(self)

    def size(self):
        return _image_editor.SizeTVector_size(self)

    def swap(self, v):
        return _image_editor.SizeTVector_swap(self, v)

    def begin(self):
        return _image_editor.SizeTVector_begin(self)

    def end(self):
        return _image_editor.SizeTVector_end(self)

    def rbegin(self):
        return _image_editor.SizeTVector_rbegin(self)

    def rend(self):
        return _image_editor.SizeTVector_rend(self)

    def clear(self):
        return _image_editor.SizeTVector_clear(self)

    def get_allocator(self):
        return _image_editor.SizeTVector_get_allocator(self)

    def pop_back(self):
        return _image_editor.SizeTVector_pop_back(self)

    def erase(self, *args):
        return _image_editor.SizeTVector_erase(self, *args)

    def __init__(self, *args):
        _image_editor.SizeTVector_swiginit(self, _image_editor.new_SizeTVector(*args))

    def push_back(self, x):
        return _image_editor.SizeTVector_push_back(self, x)

    def front(self):
        return _image_editor.SizeTVector_front(self)

    def back(self):
        return _image_editor.SizeTVector_back(self)

    def assign(self, n, x):
        return _image_editor.SizeTVector_assign(self, n, x)

    def resize(self, *args):
        return _image_editor.SizeTVector_resize(self, *args)

    def insert(self, *args):
        return _image_editor.SizeTVector_insert(self, *args)

    def reserve(self, n):
        return _image_editor.SizeTVector_reserve(self, n)

    def capacity(self):
        return _image_editor.SizeTVector_capacity(self)
    __swig_destroy__ = _image_editor.delete_SizeTVector

# Register SizeTVector in _image_editor:
_image_editor.SizeTVector_swigregister(SizeTVector)
class ImageDataVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _image_editor.ImageDataVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _image_editor.ImageDataVector___nonzero__(self)

    def __bool__(self):
        return _image_editor.ImageDataVector___bool__(self)

    def __len__(self):
        return _image_editor.ImageDataVector___len__(self)

    def __getslice__(self, i, j):
        return _image_editor.ImageDataVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _image_editor.ImageDataVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _image_editor.ImageDataVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _image_editor.ImageDataVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _image_editor.ImageDataVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _image_editor.ImageDataVector___setitem__(self, *args)

    def pop(self):
        return _image_editor.ImageDataVector_pop(self)

    def append(self, x):
        return _image_editor.ImageDataVector_append(self, x)

    def empty(self):
        return _image_editor.ImageDataVector_empty(self)

    def size(self):
        return _image_editor.ImageDataVector_size(self)

    def swap(self, v):
        return _image_editor.ImageDataVector_swap(self, v)

    def begin(self):
        return _image_editor.ImageDataVector_begin(self)

    def end(self):
        return _image_editor.ImageDataVector_end(self)

    def rbegin(self):
        return _image_editor.ImageDataVector_rbegin(self)

    def rend(self):
        return _image_editor.ImageDataVector_rend(self)

    def clear(self):
        return _image_editor.ImageDataVector_clear(self)

    def get_allocator(self):
        return _image_editor.ImageDataVector_get_allocator(self)

    def pop_back(self):
        return _image_editor.ImageDataVector_pop_back(self)

    def erase(self, *args):
        return _image_editor.ImageDataVector_erase(self, *args)

    def __init__(self, *args):
        _image_editor.ImageDataVector_swiginit(self, _image_editor.new_ImageDataVector(*args))

    def push_back(self, x):
        return _image_editor.ImageDataVector_push_back(self, x)

    def front(self):
        return _image_editor.ImageDataVector_front(self)

    def back(self):
        return _image_editor.ImageDataVector_back(self)

    def assign(self, n, x):
        return _image_editor.ImageDataVector_assign(self, n, x)

    def resize(self, *args):
        return _image_editor.ImageDataVector_resize(self, *args)

    def insert(self, *args):
        return _image_editor.ImageDataVector_insert(self, *args)

    def reserve(self, n):
        return _image_editor.ImageDataVector_reserve(self, n)

    def capacity(self):
        return _image_editor.ImageDataVector_capacity(self)
    __swig_destroy__ = _image_editor.delete_ImageDataVector

# Register ImageDataVector in _image_editor:
_image_editor.ImageDataVector_swigregister(ImageDataVector)
class ImageData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _image_editor.ImageData_swiginit(self, _image_editor.new_ImageData(*args))
    __swig_destroy__ = _image_editor.delete_ImageData

    def oiio_read(self, filename):
        return _image_editor.ImageData_oiio_read(self, filename)

    def oiio_write(self, *args):
        return _image_editor.ImageData_oiio_write(self, *args)

    def oiio_write_to(self, filename):
        return _image_editor.ImageData_oiio_write_to(self, filename)

    def set_to(self, other):
        return _image_editor.ImageData_set_to(self, other)

    def set_dimensions(self, width, height, channels):
        return _image_editor.ImageData_set_dimensions(self, width, height, channels)

    def dimensions_match(self, other):
        return _image_editor.ImageData_dimensions_match(self, other)

    def get_pixel_values(self, *args):
        return _image_editor.ImageData_get_pixel_values(self, *args)

    def get_pixel_value(self, x, y, c):
        return _image_editor.ImageData_get_pixel_value(self, x, y, c)

    def set_pixel_value(self, x, y, c, val):
        return _image_editor.ImageData_set_pixel_value(self, x, y, c, val)

    def set_pixel_values(self, *args):
        return _image_editor.ImageData_set_pixel_values(self, *args)

    def set_first_three_channels(self, *args):
        return _image_editor.ImageData_set_first_three_channels(self, *args)

    def add_values(self, x, y, r, g, b, a):
        return _image_editor.ImageData_add_values(self, x, y, r, g, b, a)

    def add_value(self, x, y, channel, val):
        return _image_editor.ImageData_add_value(self, x, y, channel, val)

    def add_pixels_into(self, x, y, pixel_values):
        return _image_editor.ImageData_add_pixels_into(self, x, y, pixel_values)

    def divide_each_pixel_by(self, vals):
        return _image_editor.ImageData_divide_each_pixel_by(self, vals)

    def mix_rgb_values(self, *args):
        return _image_editor.ImageData_mix_rgb_values(self, *args)

    def scale_pixel_values(self, x, y, scale_factor):
        return _image_editor.ImageData_scale_pixel_values(self, x, y, scale_factor)

    def scale_values(self, scale_factor):
        return _image_editor.ImageData_scale_values(self, scale_factor)

    def get_index(self, *args):
        return _image_editor.ImageData_get_index(self, *args)

    def get_width(self):
        return _image_editor.ImageData_get_width(self)

    def get_height(self):
        return _image_editor.ImageData_get_height(self)

    def get_channels(self):
        return _image_editor.ImageData_get_channels(self)

    def get_data_len(self):
        return _image_editor.ImageData_get_data_len(self)

    def get_max(self):
        return _image_editor.ImageData_get_max(self)

    def get_min(self):
        return _image_editor.ImageData_get_min(self)

    def get_average(self):
        return _image_editor.ImageData_get_average(self)

    def get_n_pixels_withc_channel_value(self, channel, value, epsilon=0.001):
        return _image_editor.ImageData_get_n_pixels_withc_channel_value(self, channel, value, epsilon)

    def get_rms(self, *args):
        return _image_editor.ImageData_get_rms(self, *args)

    def interpolate_nearest_neighbor(self, x, y):
        return _image_editor.ImageData_interpolate_nearest_neighbor(self, x, y)

    def interpolate_bilinear(self, *args):
        return _image_editor.ImageData_interpolate_bilinear(self, *args)

    def get_average_ensemble(self, x, y, half_width):
        return _image_editor.ImageData_get_average_ensemble(self, x, y, half_width)

    def get_x_y_gradients(self):
        return _image_editor.ImageData_get_x_y_gradients(self)

    def get_x_gradient(self):
        return _image_editor.ImageData_get_x_gradient(self)

    def get_y_gradient(self):
        return _image_editor.ImageData_get_y_gradient(self)

    def write_x_gradient_into(self, out_image):
        return _image_editor.ImageData_write_x_gradient_into(self, out_image)

    def write_y_gradient_into(self, out_image):
        return _image_editor.ImageData_write_y_gradient_into(self, out_image)

    def clear(self):
        return _image_editor.ImageData_clear(self)

    def flip(self):
        return _image_editor.ImageData_flip(self)

    def get_output_file_name(self):
        return _image_editor.ImageData_get_output_file_name(self)

    def get_ext(self):
        return _image_editor.ImageData_get_ext(self)

    def duplicate(self):
        return _image_editor.ImageData_duplicate(self)

    def __imul__(self, other):
        return _image_editor.ImageData___imul__(self, other)

    def __iadd__(self, other):
        return _image_editor.ImageData___iadd__(self, other)

    def subtract_then_multiply(self, sub_img, mul_img):
        return _image_editor.ImageData_subtract_then_multiply(self, sub_img, mul_img)

# Register ImageData in _image_editor:
_image_editor.ImageData_swigregister(ImageData)
class Stencil(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, half_width=1):
        _image_editor.Stencil_swiginit(self, _image_editor.new_Stencil(half_width))
    __swig_destroy__ = _image_editor.delete_Stencil

    def resize(self, new_half_width):
        return _image_editor.Stencil_resize(self, new_half_width)

    def randomize_values(self, lower_bound=-0.1, upper_bound=0.1):
        return _image_editor.Stencil_randomize_values(self, lower_bound, upper_bound)

    def get_halfwidth(self):
        return _image_editor.Stencil_get_halfwidth(self)

    def get_n_elements(self):
        return _image_editor.Stencil_get_n_elements(self)

    def get_value_offset_from_center(self, x_offset, y_offset):
        return _image_editor.Stencil_get_value_offset_from_center(self, x_offset, y_offset)

    def __call__(self, *args):
        return _image_editor.Stencil___call__(self, *args)

    def print_stencil(self):
        return _image_editor.Stencil_print_stencil(self)

# Register Stencil in _image_editor:
_image_editor.Stencil_swigregister(Stencil)
class ImageDataModifier(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _image_editor.ImageDataModifier_swiginit(self, _image_editor.new_ImageDataModifier())
    __swig_destroy__ = _image_editor.delete_ImageDataModifier

    @staticmethod
    def gamma_filter(image, gamma):
        return _image_editor.ImageDataModifier_gamma_filter(image, gamma)

    @staticmethod
    def bounded_linear_convolution(*args):
        return _image_editor.ImageDataModifier_bounded_linear_convolution(*args)

    @staticmethod
    def wrapping_linear_convolution(*args):
        return _image_editor.ImageDataModifier_wrapping_linear_convolution(*args)

    @staticmethod
    def clear(image):
        return _image_editor.ImageDataModifier_clear(image)

    @staticmethod
    def julia_set(image, center, range, fract, color_lut):
        return _image_editor.ImageDataModifier_julia_set(image, center, range, fract, color_lut)

    @staticmethod
    def convert_to_contrast_units(image):
        return _image_editor.ImageDataModifier_convert_to_contrast_units(image)

    @staticmethod
    def histogram_equalize(image, n_bins=500, ignore_alpha=False):
        return _image_editor.ImageDataModifier_histogram_equalize(image, n_bins, ignore_alpha)

    @staticmethod
    def greyscale(img):
        return _image_editor.ImageDataModifier_greyscale(img)

    @staticmethod
    def downscale(image, new_width, new_height, ignore_alpha_of_zero=False):
        return _image_editor.ImageDataModifier_downscale(image, new_width, new_height, ignore_alpha_of_zero)

    @staticmethod
    def palette_match(image, colors):
        return _image_editor.ImageDataModifier_palette_match(image, colors)

    @staticmethod
    def quantize(image, levels):
        return _image_editor.ImageDataModifier_quantize(image, levels)

    @staticmethod
    def ensemble_average(*args):
        return _image_editor.ImageDataModifier_ensemble_average(*args)

    @staticmethod
    def blend_images(img_to_blend, other_image, weight):
        return _image_editor.ImageDataModifier_blend_images(img_to_blend, other_image, weight)

    @staticmethod
    def bilinear_interpolate_each_channel(image):
        return _image_editor.ImageDataModifier_bilinear_interpolate_each_channel(image)

# Register ImageDataModifier in _image_editor:
_image_editor.ImageDataModifier_swigregister(ImageDataModifier)

